//
//  magic_name.h
//  TuxPaint
//
//  Created by happymobile on 2023/11/11.
//


MAGIC_NAME(alien)
MAGIC_NAME(blind)
MAGIC_NAME(blocks_etc)
MAGIC_NAME(bloom)
MAGIC_NAME(blur)
MAGIC_NAME(bricks)
MAGIC_NAME(calligraphy)
MAGIC_NAME(cartoon)
MAGIC_NAME(checkerboard)
MAGIC_NAME(clone)
MAGIC_NAME(colorsep)
MAGIC_NAME(confetti)
MAGIC_NAME(distortion)
MAGIC_NAME(emboss)
MAGIC_NAME(fade_darken)
MAGIC_NAME(fisheye)
MAGIC_NAME(flower)
MAGIC_NAME(foam)
MAGIC_NAME(fold)
MAGIC_NAME(fretwork)
MAGIC_NAME(glasstile)
MAGIC_NAME(googlyeyes)
MAGIC_NAME(grass)
MAGIC_NAME(halftone)
MAGIC_NAME(kaleidox)
MAGIC_NAME(kalidescope)
MAGIC_NAME(light)
MAGIC_NAME(lightning)
MAGIC_NAME(maze)
MAGIC_NAME(metalpaint)
MAGIC_NAME(mirror_flip)
MAGIC_NAME(mosaic)
MAGIC_NAME(mosaic_shaped)
MAGIC_NAME(negative)
MAGIC_NAME(noise)
MAGIC_NAME(perspective)
MAGIC_NAME(pixels)
MAGIC_NAME(puzzle)
MAGIC_NAME(rails)
MAGIC_NAME(rain)
MAGIC_NAME(rainbow)
MAGIC_NAME(realrainbow)
MAGIC_NAME(reflection)
MAGIC_NAME(ribbon)
MAGIC_NAME(ripples)
MAGIC_NAME(rosette)
MAGIC_NAME(sharpen)
MAGIC_NAME(shift)
MAGIC_NAME(smooth)
MAGIC_NAME(smudge)
MAGIC_NAME(snow)
MAGIC_NAME(stretch)
MAGIC_NAME(string)
MAGIC_NAME(swirls)
MAGIC_NAME(tint)
MAGIC_NAME(toothpaste)
MAGIC_NAME(tornado)
MAGIC_NAME(tv)
MAGIC_NAME(waves)
MAGIC_NAME(xor)


